export const DEMO_PRESETS = [
  {
    id: "noise",
    label: "Noise",
    text: "anyone up for football at 6?",
    source: "whatsapp",
    received_at: "",
  },
  {
    id: "science-hw",
    label: "Science homework",
    text: "Science lab report submission on 28th August, worth 20% of grade.",
    source: "email",
    received_at: "2026-08-20T11:00:00Z",
  },
  {
    id: "correction",
    label: "Correction (25th not 28th)",
    text: "Science report due 25th not 28th",
    source: "whatsapp",
    received_at: "2026-08-22T09:00:00Z",
  },
  {
    id: "unknown",
    label: "Unknown deadline",
    text: "English essay competition registration closes soon, don't miss it",
    source: "whatsapp",
    received_at: "2026-08-21T09:00:00Z",
  },
  {
    id: "maths-setup",
    label: "Maths worksheet (28 Aug)",
    text: "Maths worksheet 3 is due Friday 28 August.",
    source: "class",
    received_at: "2026-08-20T12:30:00Z",
  },
  {
    id: "next-friday",
    label: "Conflict: next Friday",
    text: "Maths worksheet due next Friday",
    source: "whatsapp",
    received_at: "2026-08-24T09:02:00Z",
  },
  {
    id: "this-friday",
    label: "Confirm: this Friday",
    text: "Maths worksheet deadline: this Friday",
    source: "email",
    received_at: "2026-08-25T18:40:00Z",
  },
];
